Feat: Adds tests for read-only and public functions
citycoins/citycoin pull request #27
Opened 2021-05-20 17:35 UTC by LNow

This PR introduces more Clarinet-based tests that covers read-only and public functions.

2021-05-21 23:06 UTC, whoabuddy requested changes
Very small things on my first pass, mostly missed or extra characters with typing. Two simple ones to update:

- replace `checke` with `check`
- replace `stak` with `stack`

2021-05-21 23:06 UTC, whoabuddy commented on tests/citycoin_test.ts
> +      it("succeedes and causes one stx_transfer_event", () => {
typo: `succeeds`

2021-05-21 23:06 UTC, whoabuddy commented on tests/citycoin_test.ts
> +      it("throws ERR_NOTHIG_TO_REDEEM error when stacker didn't stack at all", () => {
typo: `ERR_NOTHING_TO_REDEEM`

2021-05-21 23:06 UTC, whoabuddy commented on tests/citycoin_test.ts
> +        // mine some tokes
typo: `tokens`

2021-05-21 23:06 UTC, whoabuddy commented on tests/citycoin_test.ts
> +        // check return valu
typo: `value`

2021-05-21 23:06 UTC, whoabuddy commented on tests/citycoin_test.ts
> +        // check evens count
typo: `events`

2021-05-22 16:02 UTC, whoabuddy approved these changes

2021-05-22 16:07 UTC, asteriabtc approved these changes

2021-05-22 16:08 UTC, merged